### PR TITLE
week 8 warmup

### PR DESCRIPTION
**Pull request by ayine17**
week 8 warmup first pull

### CODE REVIEW

**Comment by cheuschober** [comment]
retest this please

**Comment by cheuschober** [comment]
@ayine17 -- for some reason all your files have a capital .PY instead of lowercase .py extension I think that's what's going wrong. Use `git mv oldname newname` to rename the files

**Comment by cheuschober** [comment]
@ayine17 You'll still want to rename your files from `.PY` to `.py` after that, I expect it will work.

**Comment by ayine17** [comment]
@cheuschober 
it still failed, after i renamed the files

**Comment by cheuschober** [comment]
@ayine17 Did you push your changes? I don't see the moved files here. I might be able to offer additional guidance if the tests weren't totally failing because of the name change.

**Pull request merged**
